name: logger_flutter
description: Flutter extension for logger. Please go there for documentation.
version: 1.0.0
homepage: https://github.com/leisim/logger_flutter
publish_to: none

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  logger:
    git: https://github.com/hieubui2409/logger.git
  sensors_plus: ">=1.3.2"
  google_fonts: ^3.0.1
dependency_overrides:
  logger:
    git: https://github.com/hieubui2409/logger.git
