name: logger_flutter_fork
description: Flutter extension for logger. Please go there for documentation.
version: 1.2.0
homepage: https://github.com/fmotalleb/logger_flutter

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  logger_fork: ^1.2.0
  sensors_plus: ^1.4.0
  share_plus: ^4.5.2
